import Footer from "./footer";
import Head from "next/head";
import Navbar2 from "./navbar2";

const Layout2 = ({ children }) => {
  return (
    <>
      <Head>
        <title>T-loc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar2 />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </div>
    </>
  );
};
export default Layout2;
