import Head from "next/head";
import Image from "next/image";
import Hotdog from "../components/hotdog";
import Menu from "../components/menu";
import { gql } from "@apollo/client";
import client from "../apolloClient";

export default function Home({ menus }) {
  return (
    <div className="bg-yellowBg">
      <Head>
        <title>T-loc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Shrikhand&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="bg-redBg min-h-screen w-full  text-center text-white flex flex-col justify-center items-center font-nmr font-bold">
        <h3 className="text-xl">T-Loc's World Famous</h3>
        <h1 className="text-9xl">SONORAN</h1>
        <h2 className="text-4xl">HOT DOGS</h2>
      </div>
      <Hotdog />

      <Menu {...menus} />
    </div>
  );
}

export async function getStaticProps() {
  const { data: menus } = await client
    .query({
      query: gql`
        query {
          menus {
            nameOfSection
            id
            items {
              itemName
              price
              description
            }
          }
        }
      `,
    })
    .catch((err) => {
      return { data: "There was an error!" };
    });
  // console.log(menus);
  return {
    props: {
      menus,
    },
  };
}
