import Head from "next/head";
import Image from "next/image";
import Hotdog from "../components/hotdog";
import Menu from "../components/menu";
import { gql } from "@apollo/client";
import client from "../apolloClient";
import NavbarHome from "../components/navbarHome";

export default function Home({ menus }) {
  return (
    <div>
      <Head>
        <title>T-loc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Shrikhand&display=swap"
          rel="stylesheet"
        />
      </Head>
      <NavbarHome />
      <div className="bg-yellowBg">
        <Hotdog />
        <Menu {...menus} />
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const { data: menus } = await client
    .query({
      query: gql`
        query {
          menus {
            nameOfSection
            id
            items {
              itemName
              price
              description
            }
          }
        }
      `,
    })
    .catch((err) => {
      return { data: "There was an error!" };
    });
  // console.log(menus);
  return {
    props: {
      menus,
    },
  };
}
