import Head from "next/head";
import Image from "next/image";
import Hotdog from "../components/hotdog";
import Menu from "../components/menu";
import { gql } from "@apollo/client";
import client from "../apolloClient";

export default function Home({ menus }) {
  return (
    <div className="bg-yellowBg">
      <Head>
        <title>T-loc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Shrikhand&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="bg-redBg h-screen w-full -mt-40 ">
        <button>click here</button>
      </div>
      <Hotdog />

      <Menu {...menus} />
    </div>
  );
}

export async function getStaticProps() {
  const { data: menus } = await client
    .query({
      query: gql`
        query {
          menus {
            id
            itemName
            description
            price
          }
        }
      `,
    })
    .catch((err) => {
      return { data: "There was an error!" };
    });
  // console.log(evnts);
  return {
    props: {
      menus,
    },
  };
}
